export const TRANSPORTERS = [
    { rut: "11958136-2", nombre: "Mario del Rosario Constanzo Ulloa", empresa: "JORQUERA" },
    { rut: "9860993-8", nombre: "Lorenzo Orlando Jiménez Belmar", empresa: "JORQUERA" },
    { rut: "14374328-4", nombre: "Héctor Omar Vergara Molina", empresa: "JORQUERA" },
    { rut: "11895954-K", nombre: "Marcelo Alejandro Paredes Silva", empresa: "JORQUERA" },
    { rut: "8189898-7", nombre: "Reinaldo Edmundo Arias Cid", empresa: "JORQUERA" },
    { rut: "10767042-4", nombre: "Carlos Ricardo Sandoval Neira", empresa: "JORQUERA" },
    { rut: "12700971-6", nombre: "Mario Alejandro Salas Espinoza", empresa: "JORQUERA" },
    { rut: "12302078-2", nombre: "Miguel Antonio Morales Araya", empresa: "JORQUERA" },
    { rut: "14509386-4", nombre: "Claudio Gonzalo Valdebenito Rodríguez", empresa: "JORQUERA" },
    { rut: "12524788-1", nombre: "Roberto Daniel Ormeño De La Hoz", empresa: "JORQUERA" },
    { rut: "16767655-3", nombre: "Silage Jesús Hellman Florov", empresa: "JORQUERA" },
    { rut: "9060365-5", nombre: "Mario Antonio Cartes Rodríguez", empresa: "JORQUERA" },
    { rut: "10966577-0", nombre: "Víctor Hugo Vega Millán", empresa: "JORQUERA" },
    { rut: "8320820-1", nombre: "Daniel Bernardo Bobadilla Salvo", empresa: "ZMC" },
    { rut: "12062638-8", nombre: "Héctor Claudio Muñoz Aravena", empresa: "JORQUERA" },
    { rut: "12701005-6", nombre: "Celso Elías Figueroa Vásquez", empresa: "JORQUERA" },
    { rut: "13104194-2", nombre: "Manuel Alejandro Torres Muñoz", empresa: "JORQUERA" },
    { rut: "18416929-0", nombre: "Cristian Alejandro Cabrera García", empresa: "JORQUERA" },
    { rut: "16863365-3", nombre: "Javier Andrés González Luna", empresa: "JORQUERA" },
    { rut: "18388976-1", nombre: "Víctor Gabriel Ovalle Díaz", empresa: "JORQUERA" },
    { rut: "13727239-3", nombre: "Alejandro Antonio Sepúlveda Bahamondes", empresa: "JORQUERA" },
    { rut: "13106421-7", nombre: "Rosamel Alejandro Parra Donoso", empresa: "JORQUERA" },
    { rut: "12697368-3", nombre: "Paola Andrea Rojas López", empresa: "JORQUERA" },
    { rut: "14353323-9", nombre: "Betsy Johanna Rivas Palma", empresa: "JORQUERA" },
    { rut: "17041364-4", nombre: "Mauricio Esteban Saura Toledo", empresa: "JORQUERA" },
    { rut: "16763911-9", nombre: "Fabián Enrique Paine Espinoza", empresa: "JORQUERA" },
    { rut: "18519374-8", nombre: "Ignacio Naim Fonseca Godoy", empresa: "JORQUERA" },
    { rut: "17572658-6", nombre: "Marcelo Andrés Sanhueza Valdebenito", empresa: "JORQUERA" },
    { rut: "17284301-8", nombre: "Felipe Ignacio Méndez Rodríguez", empresa: "JORQUERA" },
    { rut: "16738019-0", nombre: "Sergio Alexander Opazo Contreras", empresa: "JORQUERA" },
    { rut: "11986090-3", nombre: "Ángel Miguel Mansilla Villanueva", empresa: "JORQUERA" },
    { rut: "13797021-K", nombre: "Mauricio Edgardo Pérez Ormeño", empresa: "JORQUERA" },
    { rut: "14374002-1", nombre: "Rodrigo Alejandro Silva Inostroza", empresa: "JORQUERA" },
    { rut: "13721110-6", nombre: "José Gerardo Leiva Palma", empresa: "JORQUERA" },
    { rut: "10625617-9", nombre: "Julio Javier Villalobos Lara", empresa: "JORQUERA" },
    { rut: "14231839-3", nombre: "Carlos Patricio García Muñoz", empresa: "JORQUERA" },
    { rut: "15197489-9", nombre: "César Rodrigo Roca Fredes", empresa: "JORQUERA" },
    { rut: "13587603-8", nombre: "Helmutt Ernando García Valenzuela", empresa: "JORQUERA" },
    { rut: "9967959-K", nombre: "Francisco Javier Paz Gallardo", empresa: "JORQUERA" },
    { rut: "9264423-5", nombre: "Daniel Isidro Vivanco Concha", empresa: "JORQUERA" },
    { rut: "8580134-1", nombre: "Roberto Eugenio Riquelme Monteghilfo", empresa: "JORQUERA" },
    { rut: "10413517-K", nombre: "Juan Manuel Herrera Astete", empresa: "JORQUERA" },
    { rut: "14356104-6", nombre: "Luis Fernando Lara Durán", empresa: "JORQUERA" },
    { rut: "16139003-8", nombre: "César Ángelo Merino Fariña", empresa: "JORQUERA" },
    { rut: "15195407-3", nombre: "Jesús Eliseo Aedo Rozas", empresa: "JORQUERA" },
    { rut: "16139763-6", nombre: "Rubén David Sanhueza Marabolí", empresa: "JORQUERA" },
    { rut: "16035947-1", nombre: "Igor Jesús Alejandro Vallejos Sepúlveda", empresa: "JORQUERA" },
    { rut: "15854060-6", nombre: "Álvaro Rodrigo Vega Parada", empresa: "JORQUERA" },
    { rut: "17862762-7", nombre: "Héctor Andrés Salazar Mellado", empresa: "JORQUERA" },
    { rut: "16515725-7", nombre: "Mauricio Andrés Estanislao Pantoja Muñoz", empresa: "JORQUERA" },
    { rut: "15235374-K", nombre: "Eduardo Enrique Lara Aravena", empresa: "JORQUERA" },
    { rut: "14620402-3", nombre: "Denis Heraldo Arias Pereira", empresa: "JORQUERA" },
    { rut: "14271555-4", nombre: "Marcos Aurelio Freire Jeno", empresa: "JORQUERA" },
    { rut: "16153997-K", nombre: "Víctor Alfonso Muñoz Veloso", empresa: "JORQUERA" },
    { rut: "12526850-1", nombre: "Juan Erick Silva Muñoz", empresa: "JORQUERA" },
    { rut: "14273157-6", nombre: "Claudio Sergio Vergara Molina", empresa: "JORQUERA" },
    { rut: "19109792-0", nombre: "Roberto Ignacio Báez Anabalón", empresa: "JORQUERA" },
    { rut: "15955241-1", nombre: "Pablo Esteban Salinas Suazo", empresa: "JORQUERA" },
    { rut: "14293509-0", nombre: "Rodrigo Enrique Troncoso Véjar", empresa: "JORQUERA" },
    { rut: "16037173-0", nombre: "Daniel Rodrigo Morales Araya", empresa: "JORQUERA" },
    { rut: "16152270-8", nombre: "Lisandro Ernesto Pozas Vejar", empresa: "JORQUERA" },
    { rut: "15166873-9", nombre: "Franklin Alexis Torres Araya", empresa: "JORQUERA" },
    { rut: "13393900-8", nombre: "Leonardo Enrique Mora Silva", empresa: "JORQUERA" },
    { rut: "8163293-6", nombre: "Joel Hernán Caamaño Torres", empresa: "JORQUERA" },
    { rut: "14352455-8", nombre: "Pedro Alejandro Pereira Barrientos", empresa: "JORQUERA" },
    { rut: "13393467-7", nombre: "Héctor Miguel Araneda Araya", empresa: "JORQUERA" },
    { rut: "10402481-5", nombre: "Juan Carlos Aguilar Pedreros", empresa: "JORQUERA" },
    { rut: "16035906-4", nombre: "Mauricio Felipe Fernández Jara", empresa: "JORQUERA" },
    { rut: "14354154-1", nombre: "Javier Gustavo Arenas Poblete", empresa: "JORQUERA" },
    { rut: "12696688-1", nombre: "Rodrigo Marcelo Opazo Aguayo", empresa: "JORQUERA" },
    { rut: "12460759-0", nombre: "Verónica María Cáceres Frez", empresa: "JORQUERA" },
    { rut: "15670880-1", nombre: "Sandro Enoc Quezada Hernández", empresa: "JORQUERA" },
    { rut: "15192764-5", nombre: "Patricio Alexis García Palma", empresa: "JORQUERA" },
    { rut: "12978004-5", nombre: "Gualberto Vladimir Sanhueza Gajardo", empresa: "JORQUERA" },
    { rut: "12796200-6", nombre: "Mauricio Henry Pérez Constanzo", empresa: "JORQUERA" },
    { rut: "15182158-8", nombre: "Víctor Manuel Paillanao Villena", empresa: "JORQUERA" },
    { rut: "11685134-2", nombre: "Patricio Moisés Aravena Toledo", empresa: "JORQUERA" },
    { rut: "16536245-4", nombre: "Joanna Valeska Moserrat Veloso Paredes", empresa: "JORQUERA" },
    { rut: "10195105-7", nombre: "Patricio Delberto Duarte Lara", empresa: "JORQUERA" },
    { rut: "16036476-9", nombre: "Marcos Vinicio Carbachi", empresa: "JORQUERA" }
];
